version: '3'
services:
  db:
    container_name: api_db
    image: postgres:12.15
    restart: always
    ports:
      - 8080:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    command: crystal migrate.cr up

